name: Build code

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.4

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: FLAVOR=nightly make ci

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          build/s3
